module.exports = {
  VERIFY_USER: 'VERIFY_USER',
  USER_CONNECTED: 'USER_CONNECTED',
  USER_DISCONNECTED: 'USER_DISCONNECTED',
  MESSAGE_SEND: 'MESSAGE_SEND',
  MESSAGE_RECEIVED: 'MESSAGE_RECEIVED',
  TYPING: 'TYPING',
  LOGOUT: 'LOGOUT'
}
