module.exports = {
  SIGNIN:'SIGNIN',
  LOGIN: 'LOGIN',
  VERIFY_USER: 'VERIFY_USER',
  USER_CONNECT: 'USER_CONNECT',
  USER_DISCONNECT: 'USER_DISCONNECT',
  MESSAGE_SEND: 'MESSAGE_SEND',
  MESSAGE_RECEIVED: 'MESSAGE_RECEIVED',
  TYPING: 'TYPING',
  LOGOUT: 'LOGOUT'
}
