module.exports = {
  SIGNIN:'SIGNIN',
  LOGIN: 'LOGIN',
  VERIFY_USER: 'VERIFY_USER',
  USER_CONNECTED: 'USER_CONNECTED',
  USER_DISCONNECTED: 'USER_DISCONNECTED ',
  COMMUNITY_CHAT: 'COMMUNITY_CHAT',
  LOAD_CHATS: 'LOAD_CHATS',
  MESSAGE_SENT: 'MESSAGE_SENT',
  MESSAGE_RECEIVED: 'MESSAGE_RECEIVED',
  TYPING: 'TYPING',
  LOGOUT: 'LOGOUT'
}
